services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: qvema_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  db_data: